export const themes = {
  default: {
    light: {
      name: 'default',
      mode: 'light',
      menu: '#009485',
      menuBorder: '#ffff00',
      title: '#ffff00',
      primaryText: '#73ffca',
      secondaryText: '#3acaa7',
      hoverText: '#ffff00',
      disabledText: '#000',
      activeText: '#ffff00',
      background: '#bfe0e0',
      backgroundImage: 'url("/assets/bg/bg-default-light.png")',
    },
    dark: {
      name: 'default',
      mode: 'dark',
      menu: '#009485',
      menuBorder: '#ffff00',
      title: '#ffff00',
      primaryText: '#73ffca',
      secondaryText: '#3acaa7',
      hoverText: '#ffff00',
      disabledText: '#000',
      activeText: '#ffff00',
      background: '#0b2425',
      backgroundImage: 'url("/assets/bg/bg-default-dark.png")',
    },
  },
  retro: {
    light: {
      name: 'retro',
      mode: 'light',
      menu: '#FFD700',
      menuBorder: '#FF69B4',
      title: '#FF69B4',
      primaryText: '#FF4500',
      secondaryText: '#8A2BE2',
      hoverText: '#FF69B4',
      disabledText: '#000',
      activeText: '#FF69B4',
      background: '#FFF8DC',
      backgroundImage: 'url("/assets/bg/bg-retro-light.png")',
    },
    dark: {
      name: 'retro',
      mode: 'dark',
      menu: '#FF8C00',
      menuBorder: '#FF1493',
      title: '#FF1493',
      primaryText: '#32CD32',
      secondaryText: '#1E90FF',
      hoverText: '#FF1493',
      disabledText: '#000',
      activeText: '#FF1493',
      background: '#2F4F4F',
      backgroundImage: 'url("/assets/bg/bg-retro-dark.png")',
    },
  },
  neon: {
    light: {
      name: 'neon',
      mode: 'light',
      menu: '#32CD32',
      menuBorder: '#FFD700',
      title: '#FFD700',
      primaryText: '#00FFFF',
      secondaryText: '#FF00FF',
      hoverText: '#FFD700 ',
      disabledText: '#000',
      activeText: '#FFD700',
      background: '#F0FFFF',
      backgroundImage: 'url("/assets/bg/bg-retro-light.png")',
    },
    dark: {
      name: 'neon',
      mode: 'dark',
      menu: '#00FA9A',
      menuBorder: '#FF4500',
      title: '#FF4500',
      primaryText: '#00BFFF',
      secondaryText: '#FF1493',
      hoverText: '#FF4500 ',
      disabledText: '#000',
      activeText: '#FF4500',
      background: '#191970',
      backgroundImage: 'url("/assets/bg/bg-retro-dark.png")',
    },
  },
  cool: {
    light: {
      name: 'cool',
      mode: 'light',
      menu: '#4682B4',
      menuBorder: '#00CED1',
      title: '#00CED1',
      primaryText: '#1E90FF',
      secondaryText: '#5F9EA0',
      hoverText: '#00CED1',
      disabledText: '#000',
      activeText: '#00CED1',
      background: '#E0FFFF',
      backgroundImage: 'url("/assets/bg/bg-retro-light.png")',
    },
    dark: {
      name: 'cool',
      mode: 'dark',
      menu: '#00BFFF',
      menuBorder: '#7FFFD4',
      title: '#7FFFD4',
      primaryText: '#87CEFA',
      secondaryText: '#48D1CC',
      hoverText: '#7FFFD4 ',
      disabledText: '#000',
      activeText: '#7FFFD4 ',
      background: '#2C3E50',
      backgroundImage: 'url("/assets/bg/bg-retro-dark.png")',
    },
  },
  warm: {
    light: {
      name: 'warm',
      mode: 'light',
      menu: '#FFA07A',
      menuBorder: '#FFD700',
      title: '#FFD700',
      primaryText: '#FF6347',
      secondaryText: '#DB7093',
      hoverText: '#FFD700',
      disabledText: '#000',
      activeText: '#FFD700',
      background: '#FFE4E1',
      backgroundImage: 'url("/assets/bg/bg-retro-light.png")',
    },
    dark: {
      name: 'warm',
      mode: 'dark',
      menu: '#CD5C5C',
      menuBorder: '#FF4500',
      title: '#FF4500',
      primaryText: '#FF6347',
      secondaryText: '#D2691E',
      hoverText: '#FF4500 ',
      disabledText: '#000',
      activeText: '#FF4500 ',
      background: '#8B0000',
      backgroundImage: 'url("/assets/bg/bg-retro-dark.png")',
    },
  },
  // Add other themes here
};
