export const themes = {
  default: {
    label: 'Default',
    light: {
      name: 'default',
      mode: 'light',
      menu: '#009485',
      menuBorder: '#ffff00',
      title: '#ffff00',
      primaryText: '#73ffca',
      secondaryText: '#3acaa7',
      hoverText: '#ffff00',
      disabledText: '#000',
      activeText: '#ffff00',
      background: '#bfe0e0',
      backgroundClass: 'bg-default-light',
    },
    dark: {
      name: 'default',
      mode: 'dark',
      menu: '#009485',
      menuBorder: '#ffff00',
      title: '#ffff00',
      primaryText: '#73ffca',
      secondaryText: '#3acaa7',
      hoverText: '#ffff00',
      disabledText: '#000',
      activeText: '#ffff00',
      background: '#0b2425',
      backgroundClass: 'bg-default-dark',
    },
  },
  retro: {
    label: 'Retro',
    light: {
      name: 'retro',
      mode: 'light',
      menu: '#F5C046',
      menuBorder: '#FF4500',
      title: '#FF4500',
      primaryText: '#000000',
      secondaryText: '#2F4F4F',
      hoverText: '#FFFFFF',
      disabledText: '#AAAAAA',
      activeText: '#FFFFFF',
      background: '#FFF8DC',
      backgroundClass: 'bg-retro-light',
    },
    dark: {
      name: 'retro',
      mode: 'dark',
      menu: '#527853',
      menuBorder: '#EE7214',
      title: '#EE7214',
      primaryText: '#F9E8D9',
      secondaryText: '#F7B787',
      hoverText: '#EE7214',
      disabledText: '#888888',
      activeText: '#f6eb14',
      background: '#2F4F4F',
      backgroundClass: 'bg-retro-dark',
    },
  },
  neon: {
    label: 'Neon',
    light: {
      name: 'neon',
      mode: 'light',
      menu: '#32CD32',
      menuBorder: '#FFD700',
      title: '#FFD700',
      primaryText: '#00FFFF',
      secondaryText: '#FF00FF',
      hoverText: '#FFD700 ',
      disabledText: '#000',
      activeText: '#FFD700',
      background: '#F0FFFF',
      backgroundClass: 'bg-retro-dark',
    },
    dark: {
      name: 'neon',
      mode: 'dark',
      menu: '#00FA9A',
      menuBorder: '#FF4500',
      title: '#FF4500',
      primaryText: '#00BFFF',
      secondaryText: '#FF1493',
      hoverText: '#FF4500 ',
      disabledText: '#000',
      activeText: '#FF4500',
      background: '#191970',
      backgroundClass: 'bg-retro-dark',
    },
  },
  cool: {
    label: 'Cool',
    light: {
      name: 'cool',
      mode: 'light',
      menu: '#4682B4',
      menuBorder: '#00CED1',
      title: '#00CED1',
      primaryText: '#1E90FF',
      secondaryText: '#5F9EA0',
      hoverText: '#00CED1',
      disabledText: '#000',
      activeText: '#00CED1',
      background: '#E0FFFF',
      backgroundClass: 'bg-retro-dark',
    },
    dark: {
      name: 'cool',
      mode: 'dark',
      menu: '#00BFFF',
      menuBorder: '#7FFFD4',
      title: '#7FFFD4',
      primaryText: '#87CEFA',
      secondaryText: '#48D1CC',
      hoverText: '#7FFFD4 ',
      disabledText: '#000',
      activeText: '#7FFFD4 ',
      background: '#2C3E50',
      backgroundClass: 'bg-retro-dark',
    },
  },
  warm: {
    label: 'Warm',
    light: {
      name: 'warm',
      mode: 'light',
      menu: '#FFA07A',
      menuBorder: '#FFD700',
      title: '#FFD700',
      primaryText: '#FF6347',
      secondaryText: '#DB7093',
      hoverText: '#FFD700',
      disabledText: '#000',
      activeText: '#FFD700',
      background: '#FFE4E1',
      backgroundClass: 'bg-retro-dark',
    },
    dark: {
      name: 'warm',
      mode: 'dark',
      menu: '#CD5C5C',
      menuBorder: '#FF4500',
      title: '#FF4500',
      primaryText: '#FF6347',
      secondaryText: '#D2691E',
      hoverText: '#FF4500 ',
      disabledText: '#000',
      activeText: '#FF4500 ',
      background: '#8B0000',
      backgroundClass: 'bg-retro-dark',
    },
  },
  win95: {
    label: 'Win95',
    light: {
      name: 'win95',
      mode: 'light',
      menu: '#FFA07A',
      menuBorder: '#FFD700',
      title: '#FFD700',
      primaryText: '#FF6347',
      secondaryText: '#DB7093',
      hoverText: '#FFD700',
      disabledText: '#000',
      activeText: '#FFD700',
      background: '#FFE4E1',
      backgroundClass: 'bg-retro-dark',
    },
    dark: {
      name: 'win95',
      mode: 'dark',
      menu: '#c4c4c4',
      menuBorder: '#020080',
      title: '#020080',
      primaryText: '#000000',
      secondaryText: '#7d7d7d',
      hoverText: '#fbfdfd ',
      disabledText: '#000',
      activeText: '#fbfdfd ',
      background: '#8B0000',
      backgroundClass: 'bg-retro-dark',
    },
  },
  // Add other themes here
};
