export const themes = {
  default: {
    label: 'Default',
    light: {
      name: 'default',
      mode: 'light',
      menu: '#00b8a2',
      menuBorder: '#ffff66',
      title: '#ffff66',
      primaryText: '#a2ffd7',
      secondaryText: '#5df4c2',
      hoverText: '#ffff66',
      disabledText: '#666',
      activeText: '#ffff66',
      background: '#e0f7f5',
      backgroundClass: 'bg-default-light',
    },
    dark: {
      name: 'default',
      mode: 'dark',
      menu: '#009485',
      menuBorder: '#ffff00',
      title: '#ffff00',
      primaryText: '#73ffca',
      secondaryText: '#3acaa7',
      hoverText: '#ffff00',
      disabledText: '#000',
      activeText: '#ffff00',
      background: '#0b2425',
      backgroundClass: 'bg-default-dark',
    },
  },
  retro: {
    label: 'Retro',
    light: {
      name: 'retro',
      mode: 'light',
      menu: '#d2a24c',
      menuBorder: '#794a3a',
      title: '#cc6b49',
      primaryText: '#794a3a',
      secondaryText: '#537770',
      hoverText: '#ece6c2',
      disabledText: '#AAAAAA',
      activeText: '#ece6c2',
      background: '#FFF8DC',
      backgroundClass: 'bg-retro-light',
    },
    dark: {
      name: 'retro',
      mode: 'dark',
      menu: '#527853',
      menuBorder: '#EE7214',
      title: '#EE7214',
      primaryText: '#F9E8D9',
      secondaryText: '#F7B787',
      hoverText: '#EE7214',
      disabledText: '#888888',
      activeText: '#f6eb14',
      background: '#2F4F4F',
      backgroundClass: 'bg-retro-dark',
    },
  },
  neon: {
    label: 'Neon',
    light: {
      name: 'neon',
      mode: 'light',
      menu: '#F53B89',
      menuBorder: '#ffe700',
      title: '#3A0CA3',
      primaryText: '#4deeea',
      secondaryText: '#001eff',
      hoverText: '#ffe700',
      disabledText: '#BBBBBB',
      activeText: '#ffe700',
      background: '#FAF3F3',
      backgroundClass: 'bg-neon-light',
    },
    dark: {
      name: 'neon',
      mode: 'dark',
      // menu: '#1A1A2E',
      menu: '#2D2D4F',
      menuBorder: '#00FFAB',
      title: '#00D4FF',
      primaryText: '#F72585',
      secondaryText: '#9D4EDD',
      hoverText: '#00FFAB',
      disabledText: '#555555',
      activeText: '#00FFAB',
      background: '#0F3460',
      backgroundClass: 'bg-neon-dark',
    },
  },
  cool: {
    label: 'Cool',
    light: {
      name: 'cool',
      mode: 'light',
      menu: '#5BC0BE',
      menuBorder: '#0A1128',
      title: '#1B263B',
      primaryText: '#1B263B',
      secondaryText: '#3D5A80',
      hoverText: '#6FFFE9',
      disabledText: '#AAAAAA',
      activeText: '#6FFFE9',
      background: '#E0FBFC',
      backgroundClass: 'bg-cool-light',
    },
    dark: {
      name: 'cool',
      mode: 'dark',
      menu: '#1C2541',
      menuBorder: '#5BC0BE',
      title: '#70A1D7',
      primaryText: '#98C1D9',
      secondaryText: '#234D91',
      hoverText: '#BEE3DB',
      disabledText: '#444444',
      activeText: '#BEE3DB',
      background: '#0D1B2A',
      backgroundClass: 'bg-cool-dark',
    },
  },
  warm: {
    label: 'Warm',
    light: {
      name: 'warm',
      mode: 'light',
      menu: '#FF6347',
      menuBorder: '#8B0000',
      title: '#FF4500',
      primaryText: '#FFD700',
      secondaryText: '#FFA07A',
      hoverText: '#8B0000',
      disabledText: '#AAAAAA',
      activeText: '#8B0000',
      background: '#FFE4B5',
      backgroundClass: 'bg-warm-light',
    },
    dark: {
      name: 'warm',
      mode: 'dark',
      menu: '#8B0000',
      menuBorder: '#FF6347',
      title: '#FF4500',
      primaryText: '#FFD700',
      secondaryText: '#FFA07A',
      hoverText: '#FF4500',
      disabledText: '#444444',
      activeText: '#FF4500',
      background: '#3E2723',
      backgroundClass: 'bg-warm-dark',
    },
  },
  synthwave: {
    label: 'Synthwave',
    light: {
      name: 'synthwave',
      mode: 'light',
      menu: '#861df4',
      menuBorder: '#f7cc18',
      title: '#FF1493',
      primaryText: '#f7cc18',
      secondaryText: '#ea21f7',
      hoverText: '#f72871',
      disabledText: '#AAAAAA',
      activeText: '#f72871',
      background: '#E6E6FA',
      backgroundClass: 'bg-synthwave-light',
    },
    dark: {
      name: 'synthwave',
      mode: 'dark',
      menu: '#5B2A86',
      menuBorder: '#FF1493',
      title: '#FF00FF',
      primaryText: '#9C66FF',
      secondaryText: '#DA70D6',
      hoverText: '#FFD700',
      disabledText: '#555555',
      activeText: '#FFD700',
      background: '#191970',
      backgroundClass: 'bg-synthwave-dark',
    },
  },
  win95: {
    label: 'Win95',
    light: {
      name: 'win95',
      mode: 'light',
      menu: '#c4c4c4',
      menuBorder: '#020080',
      title: '#020080',
      primaryText: '#020080',
      secondaryText: '#000000',
      hoverText: '#fbfdfd',
      disabledText: '#000',
      activeText: '#fbfdfd ',
      background: '#048284',
      backgroundClass: 'bg-win95-light',
    },
    dark: {
      name: 'win95',
      mode: 'dark',
      // menu: '#1C1C1C',
      menu: '#4D4D4D',
      menuBorder: '#a957a9',
      title: '#00FFFF',
      primaryText: '#FFFFFF',
      secondaryText: '#C0C0C0',
      hoverText: '#00FFFF',
      disabledText: '#666666',
      activeText: '#00FFFF',
      background: '#000000',
      backgroundClass: 'bg-win95-dark',
    },
  },

  // Add other themes here
};
